/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectosemestral;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

/**
 *
 * @author esteb
 */
public class PantallaInicio extends javax.swing.JFrame {

    /**
     * Creates new form PantallaInicio
     */
    public PantallaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btCrear = new javax.swing.JButton();
        btProductos = new javax.swing.JButton();
        btComparar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblProductos = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lbl2productos = new javax.swing.JLabel();
        lblTipos = new javax.swing.JLabel();
        lbl32Productos = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        splitMuro1 = new proyectosemestral.SplitMuro();
        splitMuro2 = new proyectosemestral.SplitMuro();
        splitMuro3 = new proyectosemestral.SplitMuro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectosemestral/images/LogoOnsite.png"))); // NOI18N
        lblLogo.setText("jLabel1");
        bg.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 80));

        btCrear.setBackground(new java.awt.Color(31, 106, 178));
        btCrear.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btCrear.setForeground(new java.awt.Color(255, 255, 255));
        btCrear.setText("Crear");
        btCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCrear.setPreferredSize(new java.awt.Dimension(96, 34));
        bg.add(btCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 100, -1));

        btProductos.setBackground(new java.awt.Color(31, 106, 178));
        btProductos.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btProductos.setForeground(new java.awt.Color(255, 255, 255));
        btProductos.setText("Productos");
        btProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btProductos.setPreferredSize(new java.awt.Dimension(96, 34));
        bg.add(btProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        btComparar.setBackground(new java.awt.Color(31, 106, 178));
        btComparar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btComparar.setForeground(new java.awt.Color(255, 255, 255));
        btComparar.setText("Comparar");
        btComparar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btComparar.setPreferredSize(new java.awt.Dimension(96, 34));
        bg.add(btComparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(31, 106, 178));

        lblProductos.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblProductos.setForeground(new java.awt.Color(255, 255, 255));
        lblProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductos.setText("Productos");

        lblCantidad.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad.setText("Cantidad de aires acondicionados");

        lbl2productos.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lbl2productos.setForeground(new java.awt.Color(255, 255, 255));
        lbl2productos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2productos.setText("2 Productos");

        lblTipos.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblTipos.setForeground(new java.awt.Color(255, 255, 255));
        lblTipos.setText("Tipos de Instalacion");

        lbl32Productos.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lbl32Productos.setForeground(new java.awt.Color(255, 255, 255));
        lbl32Productos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl32Productos.setText("32 Productos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl2productos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(232, 232, 232)
                    .addComponent(lbl32Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(657, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(lbl2productos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(120, Short.MAX_VALUE)
                    .addComponent(lbl32Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1000, 190));

        jButton6.setBackground(new java.awt.Color(31, 106, 178));
        jButton6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Favoritos");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setPreferredSize(new java.awt.Dimension(96, 34));
        bg.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));
        bg.add(splitMuro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));
        bg.add(splitMuro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));
        bg.add(splitMuro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
    UIManager.setLookAndFeel( new FlatLightLaf() );
} catch( Exception ex ) {
    System.err.println( "Failed to initialize LaF" );
}
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btComparar;
    private javax.swing.JButton btCrear;
    private javax.swing.JButton btProductos;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl2productos;
    private javax.swing.JLabel lbl32Productos;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblTipos;
    private proyectosemestral.SplitMuro splitMuro1;
    private proyectosemestral.SplitMuro splitMuro2;
    private proyectosemestral.SplitMuro splitMuro3;
    // End of variables declaration//GEN-END:variables
}
