/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default
 * .txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to
 * edit this template
 */
package proyectosemestral;

import com.formdev.flatlaf.FlatLightLaf;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 * @author lr56c
 */
public class TestD extends javax.swing.JFrame
{

  private String stringDB = "jdbc:mysql://localhost:3306/test";
  private String user     = "root";
  //private String pass     = "Mauricio!Ignacio!Herrera!Ortega@12";
  private String pass     = "";
  private String[]          colums = { "id", "nombre" };
  private ArrayList<String[]> data   = new ArrayList<>();

  /**
   * Creates new form TestD
   */
  public TestD()
  {
    initComponents();
    data.add( new String[]{ "50", "Mauricio" });
    data.add( new String[]{ "51", "Ignacio" } );
    DefaultTableModel model  = new DefaultTableModel( data.stream().toArray(String[][]::new), colums );
    jTable1.setModel( model );
  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings( "unchecked" )
  // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(600, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(590, 590, 590))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("click");
        try
    {
      String sql = "SELECT * FROM tab";
      Connection connection = DriverManager.getConnection( stringDB, user,
        pass );

      Statement statement = connection.prepareStatement( sql );
      ResultSet resultSet = statement.executeQuery( sql );

      //String text = label.getText();
      // if(text.length > 0)
      // else System.out.println("Choose id again");

      ArrayList<String[]> lista = new ArrayList<>();

      while ( resultSet.next() )
      {
        String campo1 = resultSet.getString( 1 );
        String campo2 = resultSet.getString( 2 );
        lista.add( new String[] { campo1, campo2 } );
          System.out.println(campo2);
      }
      
      connection.close();
      
      String[][] newData = lista.stream().toArray(String[][]::new);
      DefaultTableModel model = new DefaultTableModel(newData, colums );
      jTable1.setModel( model );
      //else{
      //System.out.println("No data found");
      //}
    }
    catch ( Exception ex )
    {
        ex.printStackTrace();
      System.err.println( "Failed connection database" );
    }
    }//GEN-LAST:event_jButton1ActionPerformed

  /**
   * @param args
   *   the command line arguments
   */
  public static void main( String args[] )
  {
    /* Set the Nimbus look and feel */
    try
    {
      UIManager.setLookAndFeel( new FlatLightLaf() );
    }
    catch ( Exception ex )
    {
      System.err.println( "Failed to initialize LaF" );
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater( new Runnable()
    {
      public void run()
      {
        new TestD().setVisible( true );
      }
    } );
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
