/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Comparar;

import Entidades.VentiladorCompareDTO;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Esteban
 */
public class PantallaComparar extends javax.swing.JFrame {

    private CompararController compararController;
    private String[]          colums = { "modelo", "marca", "tipo equipo", "descripcion", "precio" };
    private ArrayList<String[]> data   = new ArrayList<>();
    private ArrayList<VentiladorCompareDTO> lista   = new ArrayList<>();
    /**
     * Creates new form PantallaComparar
     */
    public PantallaComparar() {
        
        compararController = new CompararController(this);
        
        initComponents();
        
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);
        barraBotones1.setPadre(this);
        barraBotones1.jButtonList.setEnabled(false);
        
        for (VentiladorCompareDTO ventiladorDTO : compararController.getComparaciones()) {
            
            lista.add(ventiladorDTO);
            data.add(new String[]{
                ventiladorDTO.getModelo(),
                ventiladorDTO.getMarca(),
                ventiladorDTO.getTipoEquipo(),
                ventiladorDTO.getDescripcion(),
                ventiladorDTO.getPrecio().toString()
            });
        }
        
        DefaultTableModel model  = new DefaultTableModel( data.stream().toArray(String[][]::new), colums );
        jTable1.setModel( model );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BannerSimple = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        barraBotones1 = new proyectosemestral.Paneles.BarraBotones();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BannerSimple.setBackground(new java.awt.Color(31, 106, 178));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Comparar");

        javax.swing.GroupLayout BannerSimpleLayout = new javax.swing.GroupLayout(BannerSimple);
        BannerSimple.setLayout(BannerSimpleLayout);
        BannerSimpleLayout.setHorizontalGroup(
            BannerSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BannerSimpleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(606, 606, 606))
        );
        BannerSimpleLayout.setVerticalGroup(
            BannerSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BannerSimpleLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(39, 39, 39))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(barraBotones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BannerSimple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(barraBotones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BannerSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        if(evt.getClickCount() == 2){
            int row = jTable1.getSelectedRow();
            compararController.GoItem(row);
        }
        else if(evt.getButton() == MouseEvent.BUTTON3)
        {
            // se realizo click derecho
            int row = jTable1.rowAtPoint(evt.getPoint());
            if (row >= 0 && row < jTable1.getRowCount()) {
                //se hizo click derecho en una fila que existe
                
                jTable1.setRowSelectionInterval(row, row);
                
                int respuesta = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar este producto de la comparacion?", "Eliminar comparacion", 0);
                
                if(respuesta == 0){
                    if(compararController.deleteComparacion(lista.get(row).getId())){
                        lista.remove(row);
                        data.remove(row);
                        DefaultTableModel model  = new DefaultTableModel( data.stream().toArray(String[][]::new), colums );
                        jTable1.setModel( model );
                        JOptionPane.showMessageDialog(this, "Producto eliminado correctamente", "Exito",1);
                    }
                }
            } else {
                jTable1.clearSelection();
            }
        }
    }//GEN-LAST:event_jTable1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try{
            UIManager.setLookAndFeel( new FlatLightLaf() );
} catch( Exception ex ) {
    System.err.println( "Failed to initialize LaF" );
}

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaComparar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BannerSimple;
    private proyectosemestral.Paneles.BarraBotones barraBotones1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
