/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectosemestral.Paneles;

/**
 *
 * @author lr56c
 */
public class BarraPanelCreacion extends javax.swing.JPanel {

    /**
     * Creates new form BarraPanelCreacion
     */
    public BarraPanelCreacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitleLabel = new javax.swing.JLabel();
        jBackButton = new javax.swing.JButton();
        jContinueButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jTitleLabel.setForeground(new java.awt.Color(51, 51, 51));
        jTitleLabel.setText("Modo Creacion");

        jBackButton.setBackground(new java.awt.Color(31, 106, 178));
        jBackButton.setText("Volver");

        jContinueButton.setBackground(new java.awt.Color(31, 106, 178));
        jContinueButton.setText("Enviar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 500, Short.MAX_VALUE)
                .addComponent(jTitleLabel)
                .addGap(468, 468, 468)
                .addComponent(jContinueButton)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBackButton)
                    .addComponent(jContinueButton)
                    .addComponent(jTitleLabel))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBackButton;
    public javax.swing.JButton jContinueButton;
    private javax.swing.JLabel jTitleLabel;
    // End of variables declaration//GEN-END:variables
}
